github: [BrainSAIT]
patreon: BrainSAIT
open_collective: BrainSAIT
ko_fi: BrainSAIT
tidelift: ''
community_bridge: ''
liberapay: ''
issuehunt: ''
otechie: ''
lfx_crowdfunding: ''
polar: ''
custom: ['https://www.brainsait.com/donate', 'https://brainsait.com/support']
